### ISSUE TITLE
Netmask vulnerability

### ISSUE THREAD

**Issue by maxx-nomad** [aghadiry/serverless-cloudfront-invalidate#22]
This library depends on `proxy-agent > pac-proxy-agent > pac-resolver > netmask`

https://github.com/TooTallNate/node-pac-resolver/commit/1d1a92e24351c91e96dcbdb58b5b52ead7ee8d22#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519
Here is fixed netmask vulnerability.
Please update

**Comment by javier-caylent** [comment]
Any idea about when you are thinking of fixing it guys?

**Comment by maxx-nomad** [comment]
#23 PR for fix

**Comment by coyoteecd** [comment]
@maxx-nomad @aghadiry Please close solved/merged issues, others will waste time looking at the issue list before deciding to upgrade
